/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package videojuegos.pec1;

import java.io.FileNotFoundException;
import java.util.HashMap;
import javax.swing.JFrame;
import videojuegos.pec1.armas.Arma;
import videojuegos.pec1.personajes.Druida;
import videojuegos.pec1.personajes.Kender;
import videojuegos.pec1.personajes.Nigromante;
import videojuegos.pec1.personajes.Personaje;

/**
 *
 * @author Jorge
 */
public class PantallaCrearPersonaje extends javax.swing.JFrame {

    /**
     * Creates new form CrearPersonaje
     * @throws java.io.FileNotFoundException
     */
    JFrame anterior;
    public PantallaCrearPersonaje(JFrame pantallaAnterior, Juego juego) throws FileNotFoundException {
        initComponents();
        anterior = pantallaAnterior;
        anterior.setVisible(false);
        this.setVisible(true);
        juego.iniciarDatos();
        personajes = juego.getPersonajes();
        comboRaza.setSelectedIndex(0);
    }
    Juego juego = new Juego(); 
    HashMap<String, Personaje> personajes = new HashMap<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        comboRaza = new javax.swing.JComboBox();
        labelRaza = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelPV = new javax.swing.JLabel();
        labelPM = new javax.swing.JLabel();
        textPV = new javax.swing.JTextField();
        textPM = new javax.swing.JTextField();
        labelMana = new javax.swing.JLabel();
        labelEnergia = new javax.swing.JLabel();
        textMana = new javax.swing.JTextField();
        textEnergia = new javax.swing.JTextField();
        botonOK = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        labelAtqFis = new javax.swing.JLabel();
        labelAtqMag = new javax.swing.JLabel();
        labelDefFis = new javax.swing.JLabel();
        textAtqMag = new javax.swing.JTextField();
        textDefMag = new javax.swing.JTextField();
        textAtqFis = new javax.swing.JTextField();
        textDefFis = new javax.swing.JTextField();
        labelDefMag = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        comboRaza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kender", "Nigromante", "Druida" }));
        comboRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRazaActionPerformed(evt);
            }
        });

        labelRaza.setText("Raza:");

        labelNombre.setText("Nombre: ");

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        labelPV.setText("PV: ");

        labelPM.setText("PM:");

        textPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPVActionPerformed(evt);
            }
        });

        labelMana.setText("Mana: ");

        labelEnergia.setText("Energia: ");

        textMana.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textManaPropertyChange(evt);
            }
        });

        botonOK.setText("OK");
        botonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOKActionPerformed(evt);
            }
        });

        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("PERSONAJE");

        labelAtqFis.setText("Atq. Físico:");

        labelAtqMag.setText("Atq. Mágico:");

        labelDefFis.setText("Def. Física:");

        textAtqMag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAtqMagActionPerformed(evt);
            }
        });

        textDefFis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDefFisActionPerformed(evt);
            }
        });

        labelDefMag.setText("Def. Mágica:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(separador)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelPM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelDefFis, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textDefFis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(textAtqMag, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPV, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textPM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAtqFis, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelAtqFis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelAtqMag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(labelDefMag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelMana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textDefMag)
                                    .addComponent(comboRaza, 0, 120, Short.MAX_VALUE)
                                    .addComponent(textMana)
                                    .addComponent(textEnergia, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(botonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPV)
                            .addComponent(textPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPM)
                            .addComponent(textPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAtqFis)
                            .addComponent(textAtqFis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAtqMag, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAtqMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDefFis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDefFis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDefMag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDefMag))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelRaza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnergia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPVActionPerformed

    private void textManaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textManaPropertyChange
        //VACIO 
    }//GEN-LAST:event_textManaPropertyChange

    private void comboRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRazaActionPerformed
        String seleccion = (String) comboRaza.getSelectedItem().toString();
        switch(seleccion){
            case "Kender":  {
                                textMana.setEnabled(false);
                                textEnergia.setEnabled(true);
                                break;
                            }
            case "Nigromante":  {
                                    textMana.setEnabled(true);
                                    textEnergia.setEnabled(false);
                                    break;
                                }              
            case "Druida":  {
                                textMana.setEnabled(true);
                                textEnergia.setEnabled(true);
                                break;
                            }                                
        }
    }//GEN-LAST:event_comboRazaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        juego.guardarDatos(personajes, "personajes");
        this.setVisible(false);
        anterior.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void botonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOKActionPerformed
        String seleccion = (String) comboRaza.getSelectedItem();
        String nombre = textNombre.getText();
        int pvMax = Integer.parseInt(textPV.getText());
        int pmMax = Integer.parseInt(textPM.getText());
        int atqFis = Integer.parseInt(textPM.getText());
        int atqMag = Integer.parseInt(textPM.getText());
        int defFis = Integer.parseInt(textPM.getText());
        int defMag = Integer.parseInt(textPM.getText());
        switch(seleccion){
            case "Kender":  {
                int energia = Integer.parseInt(textEnergia.getText());
                Kender personaje = new Kender(nombre, pvMax, pmMax, atqFis, atqMag, defFis, defMag, energia);
                personajes.put(nombre, personaje);
                juego.guardarDatos(personajes, "personajes");
                break;
            }
            case "Nigromante":  {
                int mana = Integer.parseInt(textMana.getText());
                Nigromante personaje = new Nigromante(nombre, pvMax, pmMax, atqFis, atqMag, defFis, defMag, mana);
                personajes.put(nombre, personaje);
                juego.guardarDatos(personajes, "personajes");
                break;
            }
            case "Druida":  {
                int energia = Integer.parseInt(textEnergia.getText());
                int mana = Integer.parseInt(textMana.getText());
                Druida personaje = new Druida(nombre, pvMax, pmMax, atqFis, atqMag, defFis, defMag, energia, mana);
                personajes.put(nombre, personaje);
                juego.guardarDatos(personajes, "personajes");
                break;
            }
        }        

    }//GEN-LAST:event_botonOKActionPerformed

    private void textAtqMagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAtqMagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAtqMagActionPerformed

    private void textDefFisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDefFisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDefFisActionPerformed

    /**
     * @param args the command line arguments
     */
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOK;
    private javax.swing.JComboBox comboRaza;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelAtqFis;
    private javax.swing.JLabel labelAtqMag;
    private javax.swing.JLabel labelDefFis;
    private javax.swing.JLabel labelDefMag;
    private javax.swing.JLabel labelEnergia;
    private javax.swing.JLabel labelMana;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPM;
    private javax.swing.JLabel labelPV;
    private javax.swing.JLabel labelRaza;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField textAtqFis;
    private javax.swing.JTextField textAtqMag;
    private javax.swing.JTextField textDefFis;
    private javax.swing.JTextField textDefMag;
    private javax.swing.JTextField textEnergia;
    private javax.swing.JTextField textMana;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPM;
    private javax.swing.JTextField textPV;
    // End of variables declaration//GEN-END:variables
}
